config/routes.rb
Rails.application.routes.draw do
  
  scope(path_names: { new: 'aplikuj' }) do
    resources :ngos,  path: 'ambasador' , only: [:index, :new, :create] do
      get 'dziekujemy', on: :collection
      get 'scrapper_city', on: :collection
      get 'raport', on: :collection
    end
  end

  get 'welcome/index'


  root to: 'welcome#index'

  #get 'seo/show'
  #get 'business_carts/index'
  #resources :cities, path: '', only: :show
  #resources :categories, path: '', only: :show
  #resources :companies, path: '', only: :show

  #devise_for :managers
  devise_for :managers, path: 'secure',  controllers: { 
  	registrations: 'managers/registrations',
  	sessions: 'managers/sessions' },
  	path_names: { sign_in: 'login',
  	sign_out: 'logout',
  	password: 'secret',
  	confirmation: 'verification',
  	unlock: 'unblock',
  	registration: 'register',
  	sign_up: 'manager' }
  	
    get 'koszyk', to: 'carts#show', as: :cart
    get 'podsumowanie', to: 'carts#resume', as: :cart_resume
    get 'platnosc', to: 'carts#payment', as: :cart_payment
    get 'potwierdzenie', to: 'carts#confirm', as: :cart_confirm
    get 'panel', to: 'carts#panel', as: :panel
    
    resources :carts, path: 'koszyk' do
      
      member do
        get 'cart'
        
      end
      collection do
        patch 'set_kind'

      end
    end

    resources :orders, path: 'zamowienia'
  
    resources :services do
      resources :cart_items, shallow: true do
      member do
          get 'configured'
        end
      end
    end
  #get 'rejestracja-firmy', to: 'company#'
  #resources :cart_bussinesses

  get 'welcome/index'
  

  scope '/biznes' do
    get 'cennik', to: 'plans#index' 
    #get 'cart', to: 'business_carts#cart', as: 'business_cart'
    resources :business_carts, path: 'koszyk' do
      collection do
        get 'cart'
      end
    end
    resources :business_cart_items
  end

  get '/:id', to: 'seo#show', as: 'seo_link'

  root 'plans#index'
  
  #scope '/biznes' do
  #  get 'cart', to: 'business_carts#index', as: 'business_cart'
  #  resources :business_cart_items, only: [:create, :update, :destroy]
  #end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
	include MultiSteps
	has_many :cart_items,  dependent: :destroy
	has_many :cart_bookings,  dependent: :destroy
	enum kind_of_booking: [:booking, :buying, :prepayment]

	def calucalte_discount
		#self.kind_of_booking
	end

	def cart_total
		sum = 0
		self.cart_items.each do |cart_item|
			cart_item.price_with_avaliable_discounts
			sum += cart_item.price_with_avaliable_discounts
		end
		sum.to_f
		puts self.id
		puts sum

		sum
		
	end

	def cart_size
	  priv_cart_size
	end

	def cart_discount_heart_count
		count = 0
		self.cart_items.each do |cart_item|
			ducat_heart = cart_item.service.booking_discount
			if ducat_heart.ducat_heart?
				count += ducat_heart.price
			end
		end
		puts count
		count
	end

	def cart_discount_affiliate_count
		count = 0
		self.cart_items.each do |cart_item|
			if self.booking?
				count += 1 if cart_item.service.booking_discount.affiliate_discount?
			elsif self.buying?
				count += 1 if cart_item.service.booking_discount.affiliate_discount?
				count += 1 if cart_item.service.buying_discount.affiliate_discount?
			elsif self.prepayment?
				count += 1 if cart_item.service.booking_discount.affiliate_discount?
				count += 1 if cart_item.service.buying_discount.affiliate_discount?
				count += 1 if cart_item.service.prepayment_discount.affiliate_discount?
			end
			#if ducat_heart.ducat_heart?
			#	count += ducat_heart.price
			#end
		end
		count
	end

	def cart_discount_standard_price
		discount = 0
		self.cart_items.each do |cart_item|
			puts cart_item.avaliable_discount
			discount += cart_item.avaliable_discount
		end
		puts discount
		discount
	end

	def cart_max_standard_discount
		discount = 0
		self.cart_items.each do |cart_item|
			puts cart_item.max_discount
			discount += cart_item.max_discount
		end
		puts discount
		discount
	end


	private

	def priv_cart_size
		cart_items.configured.size
	end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CurrentCart
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  #before_action :set_cart, only: [:cart, :show, :edit, :update, :destroy]
  #before_action :current_cart, only: [:show]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    #set_cart
    #current_cart
    @cart = current_cart
    @cart_bookings = @cart.cart_bookings
  end

  def resume
    #set_cart
    #current_cart
    @cart = current_cart
    @cart_bookings = @cart.cart_bookings
  end

  def confirm
    @cart = current_cart
    @cart_bookings = @cart.cart_bookings

    @order = Order.create(kind_of_booking: @cart.kind_of_booking,
                           price_with_ducat: @cart.cart_total,
                           heart_ducat_price: @cart.cart_discount_heart_count,
                           price: (@cart.cart_total - @cart.cart_discount_heart_count),
                           total_save: @cart.cart_discount_standard_price
)
    @cart_bookings.each do |cart_booking|
      @order_booking = OrderBooking.create(order_id: @order.id, 
                            company_id: cart_booking.company_id, 
                            date_of: cart_booking.date_of, 
                            hash_of_uniq: cart_booking.hash_of_uniq )
      cart_booking.cart_items.each do |cart_item|
        @order_item = OrderItem.create(

        order_id: @order.id,
        service_id: cart_item.service_id,
        employee_id: cart_item.employee_id,
        kind_of_booking: cart_item.kind_of_booking,
        current_step: cart_item.current_step,
        configured: cart_item.configured,
        starts_at: cart_item.starts_at,
        booking_order_id: @order_booking.id)

        
      end
     end

     @cart.destroy
  end

  def payment

  end

  def panel
    
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)
    puts params[:period] = 'sddc'
    respond_to do |format|
      if @cart.save
        format.html {  }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html {}
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def set_kind
    @cart = current_cart
    @cart_bookings = @cart.cart_bookings
    if allowed_kind_of_booking.include?(params[:kind_of_booking])
      @cart.update_attributes(kind_of_booking: params[:kind_of_booking])
    end
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Cart was successfully set.' }
      format.js 
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def allowed_kind_of_booking
      ['booking', 'buying', 'prepayment']
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end  

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to root_path, notice: "That cart doesn't exist"
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
  <span id="cart">
  <%= link_to(cart_path, class: "btn-floating btn-flat primary waves-effect- waves-light-") do  %>
    <i class="material-icons ">shopping_basket</i> 
   <% end %>
  <% unless current_cart.cart_size <= 0 %>
   <div  class="cart-size secondary"><%= current_cart.cart_size rescue '0' %></div>
   <% end %>
</span>

app/views/carts/_cart_booking.html.erb
<!-- Container >>> -->
<div class="container" >
  <div class="row">
    <div class="col l12 red- lighten-4">
      <div class="panel white row " style="padding-bottom: 0;" >
          
            
            
          <div class="col s12 l6  row  secondary-text">  
            <div class="col s5 l3 red-">
              <div class="company-logo-wrapper-">
                <div class="company-logo grey lighten-2" style="width:100px; height:100px; position:static; top:0; left:0; float:none; clear: both; margin-bottom:0;"></div>
              </div>
            </div>
  
          <div class="col s7 l9">
            <span class="right-" style="position:relative; top:35px;">
              <h3><%= cart_booking.company.name %></h3>
           </span> 
          </div>
      </div>
          
      <div class="col s12 l6 offset-l1- row  hide-">                               
        <div class="col s6 l4 center-align" style="border-top:0px solid #00acc1; padding-top: 4px !important">
          <%= configured_date(cart_booking.starts_at) %> 
        </div>
        <div class="col s6 l4 center-align " style="border-top:0px solid #00acc1; padding-top: 4px !important">
          <%= configured_starts_at(cart_booking.starts_at) %>
        </div>
        <div class="col s12 l4 center-align " style="border-top:0px solid #00acc1; padding-top: 4px !important">   
        </div>
      </div>

    </div>



    <div class="col s12 l12 offset-l1- red- lighten-4">
      <ul class="panel white collapsible- collapsible-arrow- primary-collapsible- hide-" data-collapsible="expandable" style="">
        <li class="active" id="wrapper-col">
          <div class="collapsible-body-" style="display: block;">
              
            <!-- second collapsible -->
            <ul class="collapsible- collapsible-arrow- secondary-collapsible- hide-" data-collapsible="expandable" id="category-list-">
              <li class="category-item active" style="">
                  <div class="collapsible-body secondary-collapsible-body" style="display: block;">
                    <ul class="collection " style=" position:static; float:none !important;  clear: both;">
                      <!-- cart_item do-->
                      <%= render partial: "#{action_name == 'resume' ? 'cart_item_resume' : 'cart_item'}", collection: cart_booking.cart_items, as: 'cart_item' %>
                      <!-- cart_item end-->
                        
                    </ul>
                  </div>
                </li>
              </ul>

            <!-- end second collapsible -->
          </div>
        </li>
      </ul>
    </div>
    </div>
  </div>
</div>

app/views/carts/_cart_content.html.erb
<% content_for :menu do %> <%= render partial: 'layouts/navbar_cart', locals: {step: 'first'} %> <% end %>



<div class="container">
  <div class="row no-mar-bottom">
    <div class="col s12 l9 red- lighten-4">
      <div class="panel empty no-mar-bottom" >
      <h1 class="bottom0">Koszyk</h1>
      </div>
    </div>
  </div>
</div>
<!-- <<< Container -->

<!-- Container >>> -->
<div class="container" >
  <div class="row">
    <div class="col s12 red- lighten-4">
      <div class="panel white row " >
          <div class="col s12 l12 offset-l6- row-">
            
            
              <div class="col s12 l6 offset-l3- row radio-toolbar discount_area hide- secondary-text">  <h3>Wybierz rodzaj rezerwacji</h3>i zgarnij dodatkowe bonusy!

       

          </div>
<%= form_with url: set_kind_carts_path, method: :patch, remote: true do |f| %>
          <div class="col s12 l6 offset-l1- row radio-toolbar discount_area hide-">
                                            
            <div class="col s4 l4 center-align" style="border-top:0px solid #00acc1; padding-top: 4px !important">
              
              <%= f.radio_button :kind_of_booking, 'booking', checked: @cart.booking?, id: "booking", onchange: 'Rails.fire(this.form, "submit")' %>
                    <%= f.label :kind_of_booking, 'tylko rezerwacja' , for: "booking", class: "secondary-label  mini", style: "max-width:150px;" %>
            </div>

            <div class="col s4 l4 center-align discount_area" style="border-top:0px solid #00acc1; padding-top: 4px !important">

              <%= f.radio_button :kind_of_booking, 'buying', checked: @cart.buying?, id: "buying", onchange: 'Rails.fire(this.form, "submit")'%>
               <%= f.label :kind_of_booking, 'kup teraz' , for: "buying", class: "mini", style: "max-width:150px;" %>
               
            </div>

            <div class="col s4 l4 center-align discount_area" style="border-top:0px solid #00acc1; padding-top: 4px !important">

                <%= f.radio_button :kind_of_booking, 'prepayment', checked: @cart.prepayment?, id: "prepayment", onchange: 'Rails.fire(this.form, "submit")'%>
               <%= f.label :kind_of_booking, 'kup teraz' , for: "prepayment", class: "mini", style: "max-width:150px;" do %>
                 kup teraz<br>i zapłać online
               <% end %>
            </div>
<% end %>
            </div>
        </div>
    </div>
  </div>
</div>
</div>


<%= render partial: 'cart_booking', collection: @cart_bookings %>


          




<!-- <<< Container --> 

<!-- Container >>> -->
<div class="container" style="padding-top: 0">
  <div class="row no-mar-bottom-">
    <div class="col s12 l4 red- lighten-4">
      <div class="panel center-align no-mar-bottom panel-height-200 <%= @cart.cart_discount_standard_price == 0 ? 'grey- lighten-2 grey-text text unactive' : 'white'  %>" >
      <h2>Oszczędzasz</h2>
      <br>
      <% unless @cart.cart_discount_standard_price == 0 %>

      <span class="discount badge primary- green" ><%= price_for_human(@cart.cart_discount_standard_price) %> </span><br>
      dzięki rezerwacji na <span class="primary-text">rezervi&trade;</span><br><br>
      <% else %>
      <div class="unactive-">
        <span class="discount badge primary- grey" ><%= price_for_human(@cart.cart_discount_standard_price) %> </span><br>
      </div>
     <div class="black-text">
     możesz zaoszczędzić aż
     <span class="discount- badge- primary- grey- lighten-2-" ><%= price_for_human(@cart.cart_max_standard_discount) %> </span><br>
     wybierając opcję <span class="primary-text">kup teraz i zapłać online</span><br><br>
     </div>
      <% end %>
      </div>
    </div>
    <div class="col s12 l4 blue- lighten-4">
      <div class="panel white- center-align no-mar-bottom panel-height-200 <%= @cart.cart_discount_affiliate_count == 0 ? 'grey- lighten-2 grey-text text unactive' : 'white'  %>" >
        <h2>Zyskujesz</h2><br>
   <div class="row">
    <div class="col s12">
      <span class="card_amount grey-text text-darken-2 hide-"><b></b></span><span class='card_amount grey-text text-darken-2 hide-'><%= @cart.cart_discount_affiliate_count %>x </span>
       <div id="card no-shadow" class="orange- lighten-2 center-align depth-1" style="width: 88px; height: 62px; border-radius:5px; overflow: hidden; position:relative; border:1px solid gray ;display:inline-block; margin-bottom:4px;">
            <img src="" />
            <div style="position: absolute;  bottom: 0;  margin: 0 auto;   width:100%; ">
              <div class="discount badge green ">
                <i class="material-icons tiny " style="position:relative; top:2px;">local_offer</i> 
                -&nbsp;%
              </div>
            </div>
          </div>
          <br>
          karty rabatowe na kolejne zakupy u partnerów
</div>
<div class="col s6- hide">
   <br><span class="ducat_amount grey-text text-darken-2 hide-"><b>2</b></span>   
       <span class="dukat z-depth-1 primary-text" style="background-color:yellow-; z-index:3 ;background-image: radial-gradient(#ffbf00 35%, #ffcf40 65%, #ffdc73 90%);
; color:dark; border:2px solid #a67c00; border-radius:50% !important; "><div class="center-align" style=" font-weight:bold; font-size:15px; position:relative; top:1px;"><i class="material-icons yellow-text-" style="color:#a67c00;">local_offer</i><b></b></div></span><br>
<br>Dukatów z Rabatem&trade;
</div>
</div>



                                    
      </div>
    </div>
     <div class="col s12 l4 blue- lighten-4">

      <div class="panel white center-align no-mar-bottom panel-height-200" >
        <h2>Wspierasz</h2>
        <br>
        wybraną lokalną organizaję
        <br><%= ducat_heart_count(@cart.cart_discount_heart_count) %><br>
Dukatami z Serduszkiem&trade;
      </div>
    </div>
  </div>

</div>
<!-- <<< Container --> 






<!-- Container >>> -->
<div class="container">
  <div class="row">
    <div class="col l12 red- lighten-4">
      <div class="panel white row" >
          <div class="col s12 l12 offset-l6- row">
            
             <div class="right-align">
              Razem <b><span class="total-price"><%= price_for_human(@cart.cart_total) %></span></b> 
            </div>
            <div class="col s12 l4 left-align- center-align" >
            
              <a class="waves-effect waves-light btn- btn-flat primary- secondary-text left-align-l"><i class="material-icons ">arrow_back</i><span style=" ">Wstecz</span></a>
            </div>
            <div class="col s12 l8 right-align- right-col- btn-flat  lighten-3" >
  
              <%= link_to cart_resume_path, class: 'waves-effect waves-light btn primary right-align-l' do %>
              <i class="material-icons ">forward</i><span style=" ">Podsumowanie</span>
              <% end %>
                <br><br>  <br><br> 
            </div>

          </div>
      </div>
    </div>
  </div>
</div>
<!-- <<< Container --> 

app/views/carts/_cart_discount.html.erb
  <div class="col s4 offset-l6- l4 center-align lighten-3">
    <span class="bonus-label">za rezerwację</span>
  </div>
  <div class="col s4 offset-l6- l4 center-align">
    <span class="bonus-label">za zakup online</span>
  </div>
  <div class="col s4 offset-l6- l4 center-align">
   <span class="bonus-label">za płatność online</span>
  </div>


  
  <div class="booking_discount col s4 l4 center-align min-40" >
     <%= choose_discount_kind(service.booking_discount) if service.booking_discount  %>
  </div>
  
  <div class="<%= @cart.buying? || @cart.prepayment? ? '': 'unactive' %> buying_discount col s4 l4 center-align orange- lighten-5- min-40">
   <%= choose_discount_kind(service.buying_discount) if service.buying_discount  %>


  </div>
  <div class="<%= @cart.prepayment? ? '': 'unactive' %> prepayment_discount col s4 l4 center-align orange- lighten-5- min-40">
    <%= choose_discount_kind(service.prepayment_discount) if service.prepayment_discount %>
    
  </div>
  
  <div class="col s12 offset-l6- l12 center-align min-40-">
    <div class="col s12  center-align">
    </div>
    </div> 

app/views/carts/panel.html.erb
<%= render 'layouts/admin_panel' %>

app/views/carts/resume.html.erb
<% content_for :menu do %> <%= render 'layouts/navbar_cart'%> <% end %>



<div class="container">
  <div class="row no-mar-bottom">
    <div class="col s12 l9 red- lighten-4">
      <div class="panel empty no-mar-bottom" >
      <h1 class="bottom0">Podsumowanie</h1>
      </div>
    </div>
  </div>
</div>
<!-- <<< Container -->

<!-- Container >>> -->
<div class="container" >
  <div class="row">
    <div class="col s12 red- lighten-4">
      <div class="panel white row " >
          <div class="col s12 l12 offset-l6- row-">
            
            
              <div class="col s12 l6 offset-l3- row radio-toolbar discount_area hide- secondary-text">  <h3>Wybrany rodzaj rezerwacji</h3>

       

          </div>
<%= form_with url: set_kind_carts_path, method: :patch, remote: true do |f| %>
          <div class="col s12 l6 offset-l1- row radio-toolbar discount_area hide-">
                                            
            <div class="col s4 l4 center-align" style="border-top:0px solid #00acc1; padding-top: 4px !important">
              
              <%= f.radio_button :kind_of_booking, 'booking', checked: @cart.booking?, disabled: true, id: "booking", onchange: 'Rails.fire(this.form, "submit")' %>
                    <%= f.label :kind_of_booking, 'tylko rezerwacja' , for: "booking", class: "secondary-label  mini", style: "max-width:150px;" %>
            </div>

            <div class="col s4 l4 center-align discount_area" style="border-top:0px solid #00acc1; padding-top: 4px !important">

              <%= f.radio_button :kind_of_booking, 'buying', checked: @cart.buying?, disabled: true, id: "buying", onchange: 'Rails.fire(this.form, "submit")'%>
               <%= f.label :kind_of_booking, 'kup teraz' , for: "buying", class: "mini", style: "max-width:150px;" %>
               
            </div>

            <div class="col s4 l4 center-align discount_area" style="border-top:0px solid #00acc1; padding-top: 4px !important">

                <%= f.radio_button :kind_of_booking, 'prepayment', checked: @cart.prepayment?, disabled: true, id: "prepayment", onchange: 'Rails.fire(this.form, "submit")'%>
               <%= f.label :kind_of_booking, 'kup teraz' , for: "prepayment", class: "mini", style: "max-width:150px;" do %>
                 kup teraz<br>i zapłać online
               <% end %>
            </div>
<% end %>
            </div>
        </div>
    </div>
  </div>
</div>
</div>


<%= render partial: 'cart_booking', collection: @cart_bookings %>


          




<!-- <<< Container --> 

<!-- Container >>> -->
<div class="container" style="padding-top: 0">
  <div class="row no-mar-bottom-">
    <div class="col s12 l4 red- lighten-4">
      <div class="panel center-align no-mar-bottom panel-height-200 <%= @cart.cart_discount_standard_price == 0 ? 'grey- lighten-2 grey-text text unactive' : 'white'  %>" >
      <h2>Oszczędzasz</h2>
      <br>
      <% unless @cart.cart_discount_standard_price == 0 %>

      <span class="discount badge primary- green" ><%= price_for_human(@cart.cart_discount_standard_price) %> </span><br>
      dzięki rezerwacji na <span class="primary-text">rezervi&trade;</span><br><br>
      <% else %>
      <div class="unactive-">
        <span class="discount badge primary- grey" ><%= price_for_human(@cart.cart_discount_standard_price) %> </span><br>
      </div>
     <div class="black-text">
     możesz zaoszczędzić aż
     <span class="discount- badge- primary- grey- lighten-2-" ><%= price_for_human(@cart.cart_max_standard_discount) %> </span><br>
     wybierając opcję <span class="primary-text">kup teraz i zapłać online</span><br><br>
     </div>
      <% end %>
      </div>
    </div>
    <div class="col s12 l4 blue- lighten-4">
      <div class="panel white- center-align no-mar-bottom panel-height-200 <%= @cart.cart_discount_affiliate_count == 0 ? 'grey- lighten-2 grey-text text unactive' : 'white'  %>" >
        <h2>Zyskujesz</h2><br>
   <div class="row">
    <div class="col s12">
      <span class="card_amount grey-text text-darken-2 hide-"><b></b></span><span class='card_amount grey-text text-darken-2 hide-'><%= @cart.cart_discount_affiliate_count %>x </span>
       <div id="card no-shadow" class="orange- lighten-2 center-align depth-1" style="width: 88px; height: 62px; border-radius:5px; overflow: hidden; position:relative; border:1px solid gray ;display:inline-block; margin-bottom:4px;">
            <img src="" />
            <div style="position: absolute;  bottom: 0;  margin: 0 auto;   width:100%; ">
              <div class="discount badge green ">
                <i class="material-icons tiny " style="position:relative; top:2px;">local_offer</i> 
                -&nbsp;%
              </div>
            </div>
          </div>
          <br>
          karty rabatowe na kolejne zakupy u partnerów
</div>
<div class="col s6- hide">
   <br><span class="ducat_amount grey-text text-darken-2 hide-"><b>2</b></span>   
       <span class="dukat z-depth-1 primary-text" style="background-color:yellow-; z-index:3 ;background-image: radial-gradient(#ffbf00 35%, #ffcf40 65%, #ffdc73 90%);
; color:dark; border:2px solid #a67c00; border-radius:50% !important; "><div class="center-align" style=" font-weight:bold; font-size:15px; position:relative; top:1px;"><i class="material-icons yellow-text-" style="color:#a67c00;">local_offer</i><b></b></div></span><br>
<br>Dukatów z Rabatem&trade;
</div>
</div>



                                    
      </div>
    </div>
     <div class="col s12 l4 blue- lighten-4">

      <div class="panel white center-align no-mar-bottom panel-height-200" >
        <h2>Wspierasz</h2>
        <br>
        wybraną lokalną organizaję
        <br><%= ducat_heart_count(@cart.cart_discount_heart_count) %><br>
Dukatami z Serduszkiem&trade;
      </div>
    </div>
  </div>

</div>
<!-- <<< Container --> 



<!-- Container >>> -->
<div class="container">
  <div class="row">
    <div class="col l12 red- lighten-4">
      <div class="panel white row " >

      <div class="col s12 l3 center-align- offset-l1 row radio-toolbar- discount_area hide-">
                                        
        <div id="card no-shadow empty " class="orange- lighten-2 center-align depth-1  center-align" style="width: 88px; height: 62px; border-radius:5px; overflow: hidden; position:relative; border:1px dashed gray ;display:inline-block; margin-bottom:4px;">
           
            <div style="position: absolute;  bottom: 0;  margin: 0 auto;   width:100%; ">
              <div class="discount badge grey " style="height:22.5px">
                <i class="material-icons tiny " style="position:relative; top:2px;">local_offer</i> 
                Karta
              </div>
            </div>
          </div>
          <br>
          Moje karty rabatowe rezervi&trade;<br>
          <a class="waves-effect waves-light btn primary center-align disabled"><i class="material-icons ">forward</i><span style=" ">Wybierz kartę</span></a>

</div>
      
      <div class="col s12 l5 offset-l1- row radio-toolbar- discount_area hide-">
          <h2>Oszczędź jeszcze więcej!</h2>
          <p class="grey-text">Obecnie nie masz jeszcze żadnej karty rabatowej za zakupy. <br>
          Karty rabatowe obniżają wartość koszyka. Jeśli za tą rezerwację otrzymasz kartę rabatową, będziesz mógł ją wykorzystać w przyszłości.</p>

      </div>

      <div class="col s12 l1 offset-l1- row radio-toolbar- discount_area hide-">
       
        </div>

      </div></div>
          </div>
      </div>
    </div>
  </div>
</div>
<!-- <<< Container -->


<!-- Container >>> -->
<div class="container">
  <div class="row">
    <div class="col l12 red- lighten-4">
      <div class="panel white row" >
          <div class="col s12 l12 offset-l6- row">
            
             <div class="right-align">
              Razem <b><span class="total-price"><%= price_for_human(@cart.cart_total) %></span></b> 
            </div>
            <div class="col s12 l4 left-align- center-align" >
            
              <%= link_to cart_path, class: 'waves-effect waves-light btn- btn-flat primary- secondary-text left-align-l' do %>
                <i class="material-icons ">arrow_back</i><span style=" ">Wstecz</span>
              <% end %>
            </div>
            <div class="col s12 l8 right-align- right-col- btn-flat  lighten-3" >

            <% if @cart.booking? || @cart.buying? %>
              <%= link_to cart_confirm_path, class: 'waves-effect waves-light btn primary right-align-l' do %>
              <i class="material-icons ">forward</i><span style=" ">Potwierdź rezerwację</span>
              <% end %>

            <% elsif @cart.prepayment? %>
              <%= link_to cart_payment_path, class: 'waves-effect waves-light btn primary right-align-l' do %>
              <i class="material-icons ">forward</i><span style=" ">Płatność</span>
              <% end %>
            <% end %>
                <br><br>  <br><br> 
            </div>

          </div>
      </div>
    </div>
  </div>
</div>
<!-- <<< Container --> 

app/views/carts/set_kind.js.erb
//alert('ok');
//open_modal();
$('#cart_content').html('<%= j render partial: "cart_content" %>');
$('#cart_navbar').html('<%= j render partial: "layouts/navbar_cart" %> ')

app/views/carts/show.html.erb
<div id="cart_content"><%= render partial: 'cart_content' %></div>