config/routes.rb
Rails.application.routes.draw do
  
  scope(path_names: { new: 'aplikuj' }) do
    resources :ngos,  path: 'ambasador' , only: [:index, :new, :create] do
      get 'dziekujemy', on: :collection
      get 'scrapper_city', on: :collection
      get 'raport', on: :collection
    end
  end

  get 'welcome/index'


  root to: 'welcome#index'

  #get 'seo/show'
  #get 'business_carts/index'
  #resources :cities, path: '', only: :show
  #resources :categories, path: '', only: :show
  #resources :companies, path: '', only: :show

  #devise_for :managers
  devise_for :managers, path: 'secure',  controllers: { 
  	registrations: 'managers/registrations',
  	sessions: 'managers/sessions' },
  	path_names: { sign_in: 'login',
  	sign_out: 'logout',
  	password: 'secret',
  	confirmation: 'verification',
  	unlock: 'unblock',
  	registration: 'register',
  	sign_up: 'manager' }
  	
    get 'koszyk', to: 'carts#show', as: :cart
    get 'podsumowanie', to: 'carts#resume', as: :cart_resume
    get 'platnosc', to: 'carts#payment', as: :cart_payment
    get 'potwierdzenie', to: 'carts#confirm', as: :cart_confirm
    get 'panel', to: 'carts#panel', as: :panel
    
    resources :carts, path: 'koszyk' do
      
      member do
        get 'cart'
        
      end
      collection do
        patch 'set_kind'

      end
    end

    resources :orders, path: 'zamowienia'
  
    resources :services do
      resources :cart_items, shallow: true do
      member do
          get 'configured'
        end
      end
    end
  #get 'rejestracja-firmy', to: 'company#'
  #resources :cart_bussinesses

  get 'welcome/index'
  

  scope '/biznes' do
    get 'cennik', to: 'plans#index' 
    #get 'cart', to: 'business_carts#cart', as: 'business_cart'
    resources :business_carts, path: 'koszyk' do
      collection do
        get 'cart'
      end
    end
    resources :business_cart_items
  end

  get '/:id', to: 'seo#show', as: 'seo_link'

  root 'plans#index'
  
  #scope '/biznes' do
  #  get 'cart', to: 'business_carts#index', as: 'business_cart'
  #  resources :business_cart_items, only: [:create, :update, :destroy]
  #end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  include MultiSteps
  attr_writer :current_step

  belongs_to :cart
  belongs_to :service 
  belongs_to :employee, optional: true

  enum kind_of_booking: [:booking, :prepayment]
  #enum current_step: [:employee, :datetime]
  before_validation :set_random_employee
  after_create :set_kind_of_booking_on_cart
  #before_save :update
  before_update :set_configured
  
  scope :configured, ->  { where(configured: true)}
 # with_options if: => lambda { |o| o.current_step == "select_employee" } do |item|
  #  item.custom_employee if employee_id == 0 || employee_id == nil
 #   item.validates_presence_of :employee_id
#end

  validates :employee_id, presence: true, :if => lambda { |o| o.current_step == "select_employee" }
  validates :starts_at, presence: true, :if => lambda { |o| o.current_step == "select_employee" }
  
  def price_with_avaliable_discounts
    service = self.service
    cart = self.cart
    case cart.kind_of_booking
    when 'booking'
      price = service.price - service.price_booking_discount
    when 'buying'  
      price = service.price - service.price_booking_discount - service.price_buying_discount
    when 'prepayment'
      price = service.price - service.price_booking_discount - service.price_buying_discount - service.price_prepayment_discount
    end
    price
  end

  def avaliable_discount
    self.service.price - self.price_with_avaliable_discounts
  end

  def max_discount
    service = self.service
    discount = service.price_booking_discount + service.price_buying_discount + service.price_prepayment_discount
  end

  

  def steps
    [
      select_employee: {name: 'Pracownik', icon: 'person'},
      select_datetime: {name: 'Termin', icon: 'event'} 

    ]
  end

  def step_index(custom)
    self.avaliable_steps.index(custom)
  end

  def this_step
    self.avaliable_steps[self.current_step]
  end

  def current_step_index
    self.current_step
  end
  

  
  ### method to calculate avaliable time to reservation

  def duration_of_service
    self.service.duration #in minutes
  end

  def check_avaliable_opening_hours(date) 
    unless self.service.company.company_opening_at(date) == 'closed'
      unless self.employee.employee_opening_at(date) == 'closed'
        'open'
      end
    end
  end 

  private

  def set_random_employee
    if self.employee_id == 0 #&& steps[self.current_step] == 'select_employee'
     self.employee_id = self.service.company.employee_ids.sample 
    end
  end

  def can_choose_employee?
    self.service.company.employee_ids.size > 1
  end

  def set_kind_of_booking_on_cart
    self.cart.update_attribute(:kind_of_booking, :prepayment) if self.kind_of_booking == 'prepayment'
  end

  def set_configured
    #puts 'configured?'
    puts "self.this_step: #{self.this_step}"
    puts "self.last_Step: #{self.avaliable_steps.last}"
    #puts self.configured?
    puts "self.configured? #{self.configured?}"

    puts "starts_at #{self.starts_at}"
    puts "starts_at.blank? #{self.starts_at.blank?}"
    puts "starts_at.nil? #{self.starts_at == nil}"
    puts "self.valid? #{valid?}"
    puts "self.errors #{self.errors.messages}"
    puts "1 #{self.this_step == avaliable_steps.last}"
    puts "2 #{self.valid?}"
    puts "avaliable_steps: #{avaliable_steps}"
    if self.valid? && self.this_step == avaliable_steps.last
      #puts "self.configured? #{self.configured?}"
    elsif self.valid?
      #puts "current step in out: #{self.current_step = self.next_step}"
      #self.update_attribute(:configured, true)
      #self.current_step = avaliable_steps[self.next_step]
      #self[:current_step] = avaliable_steps[self.next_step]
      #self.attributes = {current_step: avaliable_steps[self.next_step]}
      #puts self.next_step
      #puts "current step: #{self.current_step = self.next_step}"
    else
      #puts "self.configured? #{self.configured?}"
      #self.configured = false
    end
     #puts "starts_at #{self.starts_at}"
     #puts "starts_at.blank? #{self.starts_at.blank?}"
     #puts self.current_step
  end

end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
	include CurrentCart
  before_action :set_cart_item, only: [:show, :edit, :update, :destroy, :configured]
  before_action :set_cart, only: [:new, :create]
  before_action :set_service, only: [:new, :create]
  # GET /_cart_items
  # GET /_cart_items.json
  def index
    @cart_items = CartItem.all
  end

  # GET /_cart_items/1
  # GET /_cart_items/1.json
  def show
   @date = params[:date] ? Date.parse(params[:date]) : Date.today
   @service = @cart_item.service
   @company = @service.company
   @employees = @service.company.employees
   @employee = Employee.find(@cart_item.employee_id)
    respond_to do |format|
      format.html
      #format.json { head :no_content }
      format.js
    end
  end

  # GET /_cart_items/new
  def new
    @cart_item = CartItem.new
  end

  # GET /_cart_items/1/edit
  def edit

  end

  # POST /_cart_items
  # POST /_cart_items.json
  def create
   	#@cart_item = CartItem.new
    
   	@cart_item = @service.cart_items.build(cart_item_params)
    set_current_cart
    @employees = @service.company.employees
    #raise params.inspect
       respond_to do |format|
      if @cart_item.save
      	#puts @cart_item.kind_of_booking
        format.html {  }
        format.json { render :show, status: :created, location: @cart_item }
        format.js
      else
        format.html { render :new }
        format.json { render json: @cart_item.errors, status: :unprocessable_entity }
        format.js
      end
    end
    puts '--C'
  end

  # PATCH/PUT /_cart_items/1
  # PATCH/PUT /_cart_items/1.json
  def update
       @service = @cart_item.service
   @company = @service.company
   @employees = @service.company.employees
  #if @cart_item.this_step > :select_employee
  @employee = Employee.find(@cart_item.employee_id) if @cart_item.employee_id.present?
  #end


    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    puts 'date'
    puts @date
    if @cart_item.valid?
      if params[:cart_item][:back_button]     
        #puts 'VALID?'
        #puts @cart_item.valid?
        @cart_item[:current_step] = @cart_item.previous_step
        #params.delete :back_button
        #puts params

      else #@cart_item.valid?
       

         if @cart_item.this_step == @cart_item.avaliable_steps.last
          @cart_item[:configured] = true
         end
        
         @cart_item[:current_step] = @cart_item.next_step

      end
    #else
    puts "NOT VALID"  
    end
    ###
    ###

    if @cart_item.update(cart_item_params)
        puts @cart_item.configured

      if @cart_item.configured?
         cart_booking = CartBooking.find_or_create_by(cart_id: @cart_item.cart_id, company_id: @cart_item.service.company_id, date_of: @cart_item.starts_at)
         @cart_item.cart_booking_id = cart_booking.id
         @cart_item.save
         render 'configured'
      else

        respond_to do |format|
          format.html { redirect_to carts_path  }
          format.json { render :show, status: :ok, location: @cart_item }
          format.js
        end
      
      end
    else
        respond_to do |format|
          format.html { render :edit }
          format.json { render json: @cart_item.errors, status: :unprocessable_entity }
          format.js
      end
     
    end
  end

  # GET /_cart_items/1/configured
  def configured
    respond_to do |format|
    format.html { render 'configured' }
    #format.json { render :configured, status: :ok, location: @cart_item }
    format.js 
    end
  end

  # DELETE /_cart_items/1
  # DELETE /_cart_items/1.json
  def destroy
    @cart_item.destroy
    respond_to do |format|
      format.html
      #format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart_item
      @cart_item = CartItem.find(params[:id])
    end

    def set_service
      @service = Service.find(params[:service_id])
    end

    def set_current_cart
      @cart_item.cart_id = current_cart.id
    end

    # Never trust parameters from the scary internet, only allow the whitelist through.
  def cart_item_params
    #params.require(:cart_item).permit(:kind_of_booking, :service_id, :cart_id)
    params.require(:cart_item).permit(:service_id, :kind_of_booking, :cart_id, :cart_booking_id, :employee_id, :current_step, :starts_at)
  end

end

app/helpers/cart_items_helper.rb
module CartItemsHelper

	def link_to_previous_step(f)
		puts 'BACK?'
		puts @cart_item.show_back_button?
		puts @cart_item.id
		puts @cart_item.avaliable_steps.first
		puts @cart_item.first_step?
		puts @cart_item.last_step?
		puts @cart_item.avaliable_steps.index(@cart_item.this_step)
		puts @cart_item.current_step
		puts @cart_item.current_step == @cart_item.avaliable_steps.index(@cart_item.this_step)
		if @cart_item.show_back_button?
		f.button "wstecz", name: "cart_item[back_button]", class: "waves-effect waves-light btn- btn-flat primary- secondary-text left-align-l" do
		#content_tag(:button, "wstecz"
			content_tag(:i, "arrow_back", class: "material-icons ") + content_tag(:span, "Wstecz")
			end
		end

	end


	def configured_employee(employee)
		name = employee.first
		job = employee.last
		content_tag(:span) do
			content_tag(:i, "person", class: 'material-icons icon-summary') +
			content_tag(:b, name) + ' ' +
			content_tag(:span, "#{ job}", class: "grey-text text-darken-2")
		end
	end

	def configured_date(date)
		#date = employee.first
		formatted_date = date_with_month_pl_dop(date)
		formatted_day = day_of_week_pl(date)
		content_tag(:span) do
			content_tag(:i, "event", class: 'material-icons icon-summary') +
			content_tag(:b, formatted_date) + ' ' +
			content_tag(:span, "(#{ formatted_day})", class: "grey-text text-darken-2")
		end
	end

	def configured_starts_at(date)
    	formatted_time = date.strftime("%H:%M")
		content_tag(:span) do
			content_tag(:i, "watch_later", class: 'material-icons icon-summary') +
			content_tag(:b, formatted_time)
		end
	end

end

app/views/cart_items/_configured.html.erb
  <div class="row ">
                        <div class="col s12 m8 offset-m2 l8 offset-l2 card z-depth-4 no-pad- secondary-bg  ">
                          <div class=" white-text-">
                          <h2>Brawo! Dodałeś nową usługę do koszyka rezerwacji <div class="right secondary-bg-"><a class="btn white secondary-text close_modal"><i class="material-icons right-align secondary-text- " style="position:absolute; top:0.5em;right:0.5em;">close</i></a></div></h2>
                          </div>
                          <ul class="collection ">
                              <li class="collection-item switcher- card no-pad no-shadow no-shadow photo panel-expendable-" style="border:bottom:2px solid transparent;">
                                     <%= render partial: 'seo/service_header', locals: {service: @cart_item.service} %>



                                      <div class="col s12 l6 right-col photo-padding switcher-handler- ">
                                        <i class="material-icons icon-summary hide" style="">local_offer</i>
                                        <span class="secondary-text margin-left-50- hide"> tylko rezerwacja</span> 
                                   
                                        <%= configured_employee(@cart_item.employee.name_with_job) %>
                                         
                                           
                                          <div class="employee-photo-mini- grey z-depth-1- circle- light-bg "></div>
                                          
                                          <%= configured_date(@cart_item.starts_at) %><br>            
                  
                                 
                                          <%= configured_starts_at(@cart_item.starts_at) %>  

                                      </div>
                                      <div class="col s12 l6 row  bonus-frame extra extra-m- content- hide-on-small-only-">
                                        
                                        
                                         
                                     
                                    </div>
                            </ul>
                            <div class="col s12 l9 offset-l3 row hide">
                                      <div class="col s12 l7 left-align- center-align- btn-flat" >
                                      
                                        <a class="waves-effect waves-light btn white secondary-text btn-flat- primary- secondary-text left-align-l hide"><i class="material-icons ">add_circle</i><span style=" ">Dodaj kolejną usługę</span></a>
                                         <a class="waves-effect waves-light btn secondary left-align-l"><i class="material-icons ">add_circle</i><span style=" ">Dodaj kolejną usługę</span></a>
                                      </div>
                                      <div class="col s12 l5 right-align- right-col- btn-flat  lighten-3" >
                            
                                        <a class="waves-effect waves-light btn primary right-align-l"><i class="material-icons ">shopping_basket</i><span style=" ">Przejdź do koszyka</span></a>
                                          <br><br>  <br><br> 
                                      </div>

                                    </div>
                       
                            <div class="col s12 l12 offset-l3- row hide-">
                                      <div class="col s12 l7 left-align" >
                                        <a class="waves-effect waves-light btn white secondary-text secondary- close_modal"><i class="material-icons left">add_circle</i> Dodaj kolejną usługę</a>
                                      </div>
                                      <div class="col s12 l5 right-align right-col btn-flat  lighten-3" >
                                        <a class="waves-effect waves-light btn primary lighten-1- hide"> <i class="material-icons left">shopping_basket</i>Przejdź do Koszyka</a>
                                        <%= link_to(cart_path, class: "waves-effect waves-light btn primary") do  %>
                                           <i class="material-icons left">shopping_basket</i>Przejdź do Koszyka
                                        <% end %>
                                      </div>
                                    </div>
                          </div>
                        </div>
                     
</div>

app/views/cart_items/_current_step.html.erb
<div class="row " style="z-index: 9999; ">
  <div class="col s12 m8 offset-m2 l8 offset-l2 card z-depth-4- no-pad- ">

    <h2>Nowa rezerwacja</h2>
      <ul class="collection " >
        <li class="collection-item switcher- card no-pad no-shadow no-shadow photo panel-expendable-" style="border:bottom:2px solid transparent;">
          
          <%= render partial: 'seo/service_header', locals: {service: @cart_item.service} %>
          
          <div class="col s12 l6 row  bonus-frame extra extra-m- content- hide-on-small-only-">
                                        
                                        
            <div class="container-progress-step vertical-align- grey- white pin-bar-s" style="z-index:999;" >
              <ul class="progress-step <%= @cart_item.length_of_step %>">
                                   
                <% @cart_item.steps.first.keys.each do |index| %> 
                             
                <li class=" <%= @cart_item.step_index(index) == @cart_item.current_step_index ? 'in_progress' :" "%>
                            <%= @cart_item.step_index(index) < @cart_item.current_step_index ? 'done' :" "%>
                 <%= @cart_item %>"><i class="material-icons icon"><%= @cart_item.steps.first[index.to_sym][:icon] %></i> <%= @cart_item.steps.first[index.to_sym][:name] %></li>
                <% end %>                                               
              </ul>
            <div class="col s12 l6 offset-l6 row hide show-on-small-only">
              <div class="col s4 l4 left-align-" >
                WSTECZ
              </div>
              <div class="col s8 l8 right-align- right-col- btn-flat  lighten-3" >
                <a class="waves-effect waves-light btn primary lighten-1- center-align"> <i class="material-icons left- center-align">forward</i>Pracownik</a>
             </div>

            </div>
          </div>

<% @cart_item.current_step %> <% @cart_item.this_step.to_s %>


    
                                 <%= render partial: @cart_item.this_step.to_s, locals: { employees: @employees}    %>
                          </div>
                        </div>
                      </li>
                    </ul>
                  </div>



                </div>

app/views/cart_items/_select_datetime.html.erb
<%= form_with url: cart_item_path(@cart_item), model: @cart_item, method: :put do |f| %>

                                      
                                      <div class="col s12 center-align bonus-label- radio-toolbar employees secondary-text- grey- lighten-2- grey- lighten-3-"> 
                                          <br>
                                      <h3>Wybierz termin</h3>

                                        </div>
                                       
                                   <div class="calendar">
                                         <div class="calendar-header  col s12">
                                           
                                           <%= link_to '<i class="material-icons">navigate_before</i>'.html_safe, date: @date.prev_month, class: 'material-icons' ,remote: true %>
                                            <%= @date.month rescue 'resq' %>
                                           <%= link_to '<i class="material-icons">navigate_next</i>'.html_safe, date: @date.next_month, class: 'material-icons' ,remote: true %>

                                            <%= link_to '<i class="material-icons">navigate_before</i>'.html_safe, date: @date.prev_year, class: 'material-icons' ,remote: true %>

                                             <%= @date.year rescue 'resq' %>
                                           
                                           <a class="material-icons right- hide">navigate_next</a>
                                           
                                           <%= link_to '<i class="material-icons">navigate_next</i>'.html_safe, date: @date.next_year, class: 'material-icons' ,remote: true %>
                                         </div>
                                       <table>
                                         <tr class="days-of-week center-align">
                                            <td></td>
                                            <td>Pn</td>
                                            <td>Wt</td>
                                            <td>Śr</td>
                                            <td>Cz</td>
                                            <td>Pt</td>
                                            <td>Sb</td>
                                            <td>N</td>
                                            <td></td>
                                          </tr>
                                          <tr>
                                            <td>
                                               <a class="material-icons unactive hide">navigate_before</a>
                                               <%= link_to '<i class="material-icons">navigate_before</i>'.html_safe, date: @date.prev_week, class: 'material-icons' ,remote: true %>
                                            </td>
                                           <%= @cart_item.id %>
                                            <%= @service.id  rescue '' %>
                                            <%= @date %><br>
                                            <%= week = @date.beginning_of_week..@date.end_of_week %>
                                            <%= @date.strftime("%A")  rescue 'oo' %><br>

                                            <%= x = OpeningHours.standard.where(openingable_type: 'Company', openingable_id: @service.company.id, day_of_week: @date.strftime("%A")).take rescue 'nil' %>
                                            opened: <%= x.opened rescue '' %><br> closed? <%= x.closed? rescue '' %><br>
                                            od do<%= x.start_time..x.end_time rescue ''%> <br>
                                             all_of_day?<%= x.all_of_day rescue '' %> 
                                            <br>
                                            Teraz jest + 10 minutes <%= now = Time.now + 10.minutes %>
                                            
                                            <br>
                                           STD Comp HOURES <%= @service.company.standard_opening_company_at(@date)  rescue '' %>
                                           <br>
                                           NSTD Comp HOURES <%= @service.company.non_standard_opening_company_at(@date) rescue '' %><br>

                                           CALC Comp HOURES <%= @service.company.company_opening_at(@date) rescue ''%>

                                            <br>
                                            STD Empl HOURES <%= @employee.standard_opening_employee_at(@date) rescue '' %><br>
                                            NSTD Empl HOURES <%= @employee.non_standard_opening_employee_at(@date) rescue '' %><br>
                                           

                                            Calc Empl HOURES<%= @employee.employee_opening_at(@date) rescue '' %><br>

                                            TEST STEP <% @employee.avaliable_slots(@date)  rescue 'nil' %>
                                            
                                            <% week.each do |day| %>
                                            <td>
                                              <%=  %>
                                              <%= link_to "<div class='icon #{day == @date ? 'active' : ''} #{day.past? ? 'busy' : ''} #{ @service.company.company_opening_at(day) == 'closed'  ? 'busy' : '' rescue ''}'>#{day.day}</div>".html_safe, date: day, remote: true %>
                                            </td>
                                            <% end %>
                                            <div class='hide'>
                                              
                                          </div>
                                            <td>
                                               <a class="material-icons right- hide">navigate_next</a>
                                               <%= link_to '<i class="material-icons">navigate_next</i>'.html_safe, date: @date.next_week, class: 'material-icons' ,remote: true %>
                                            </td>
                                          </tr>
                                          
                                        </table>

                                     </div>



                                  
                                  <div class="col s12 offset-l6- l12 center-align min-40-">
                                          <div class="col s12  center-align" >
                                          </div>
                                        </div>

                                    <div class="col s12 l12s row radio-toolbar employees- calendar-hours " style="max-height:250px; overflow-y:auto;">
                                      
                                      <div class="col s4 l4 center-align " style="border-top:0px solid #00acc1; padding-top: 4px !important">
                                       <span class="houres_cat grey-text">do 12:00</span>
                                       
                                           
                                        <% if @employee != nil && @employee.avaliable_slots(@date) != 'zero' %>
                                          <%= @employee.avaliable_slots(@date)[:before_midnight].each do |slot|  %>
                                          <%= f.radio_button :starts_at, slot, id: "#{slot}" rescue '' %>
                                          <%= f.label slot.strftime("%H:%M"), for: "#{slot}", class: 'standard' rescue '' %>
                                       <% end %>

                                        

                                        

                                        <% else %>

                                          <p><span class="grey-text"><br> brak wolnych terminów</span></p>

                                        <% end %>


                                      
                   
                                         

                                          
                                      </div>

                                      <div class="col s4 l4 center-align " style="border-top:0px solid #00acc1; padding-top: 4px !important">
                                        <span class="houres_cat grey-text">12:00-16:00</span>
                                      
                                      <% if @employee != nil && @employee.avaliable_slots(@date) != 'zero' %>
                                          <% @employee.avaliable_slots(@date)[:between_midnight_and_sixteen].each do |slot|  %>
                                          <%= f.radio_button :starts_at, slot, id: "#{slot}" rescue '' %>
                                          <%= f.label slot.strftime("%H:%M"), for: "#{slot}", class: 'standard' rescue '' %>
                                       <% end %>

                                        

                                        

                                        <% else %>

                                          <p><span class="grey-text"><br> brak wolnych terminów</span></p>

                                        <% end %>

                                          
                                      </div>


                                      <div class="col s4 l4 center-align " style="border-top:0px solid #00acc1; padding-top: 4px !important">
                                        <span class="houres_cat grey-text">Od 16:00</span>
                                      
                                      <% if @employee != nil && @employee.avaliable_slots(@date) != 'zero' %>
                                          <% @employee.avaliable_slots(@date)[:after_sixteen].each do |slot|  %>
                                          <%= f.radio_button :starts_at, slot, id: "#{slot}" rescue '' %>
                                          <%= f.label slot.strftime("%H:%M"), for: "#{slot}", class: 'standard' rescue '' %>
                                       <% end %>

                                        

                                        

                                        <% else %>

                                          <p><span class="grey-text"><br> brak wolnych terminów</span></p>

                                        <% end %>

                                          
                                      </div>

                                          


                                    
                                    
                                      
                            


                                    
                          
                                    
                                      
                                      <!-- -->
                                      

                                     
                                


                                      
                                          
                                

                                      </div>

                            <div class="col s12 l6- offset-l6- row">
                                      <div class="col s12 l6 left-align- center-align" >
                                       
                                        
                                         <%= link_to_previous_step(f) %>
                                      </div>
                                      <div class="col s12 l6 right-align right-col- btn-flat  lighten-3" >
                                       <%= f.button "rezerwuj", class: "btn primary open_modal-" do %>
                                          <i class="material-icons left ">forward</i> Zakończ
                                        <% end %>

                                      
                                          <br><br>  <br><br> 
                                      </div>

                                    </div>

                                    <% end %>
                          </div>
                        </div>
                      </li>
                    </ul>
                  </div>



                </div>