config/routes.rb
Rails.application.routes.draw do
  
  scope(path_names: { new: 'aplikuj' }) do
    resources :ngos,  path: 'ambasador' , only: [:index, :new, :create] do
      get 'dziekujemy', on: :collection
      get 'scrapper_city', on: :collection
      get 'raport', on: :collection
    end
  end

  get 'welcome/index'


  root to: 'welcome#index'

  #get 'seo/show'
  #get 'business_carts/index'
  #resources :cities, path: '', only: :show
  #resources :categories, path: '', only: :show
  #resources :companies, path: '', only: :show

  #devise_for :managers
  devise_for :managers, path: 'secure',  controllers: { 
  	registrations: 'managers/registrations',
  	sessions: 'managers/sessions' },
  	path_names: { sign_in: 'login',
  	sign_out: 'logout',
  	password: 'secret',
  	confirmation: 'verification',
  	unlock: 'unblock',
  	registration: 'register',
  	sign_up: 'manager' }
  	
    get 'koszyk', to: 'carts#show', as: :cart
    get 'podsumowanie', to: 'carts#resume', as: :cart_resume
    get 'platnosc', to: 'carts#payment', as: :cart_payment
    get 'potwierdzenie', to: 'carts#confirm', as: :cart_confirm
    get 'panel', to: 'carts#panel', as: :panel
    
    resources :carts, path: 'koszyk' do
      
      member do
        get 'cart'
        
      end
      collection do
        patch 'set_kind'

      end
    end

    resources :orders, path: 'zamowienia'
  
    resources :services do
      resources :cart_items, shallow: true do
      member do
          get 'configured'
        end
      end
    end
  #get 'rejestracja-firmy', to: 'company#'
  #resources :cart_bussinesses

  get 'welcome/index'
  

  scope '/biznes' do
    get 'cennik', to: 'plans#index' 
    #get 'cart', to: 'business_carts#cart', as: 'business_cart'
    resources :business_carts, path: 'koszyk' do
      collection do
        get 'cart'
      end
    end
    resources :business_cart_items
  end

  get '/:id', to: 'seo#show', as: 'seo_link'

  root 'plans#index'
  
  #scope '/biznes' do
  #  get 'cart', to: 'business_carts#index', as: 'business_cart'
  #  resources :business_cart_items, only: [:create, :update, :destroy]
  #end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/plan.rb
class Plan < ApplicationRecord

  before_destroy :not_referenced_by_any_business_cart_item
  belongs_to :manager, optional: true
  has_many :business_cart_items
  has_many :subscriptions

  validates :price, numericality: { only_integer: true }, length: { maximum: 7 }

  TIME_OPTIONS_ALL = {'test' => '14 dni testu',
   '1month' => '1 miesiąc',
   '3months' => '3 miesiące (-5%)',
   '6months' => '6 miesięcy (-10%)',
   '12months' => '12 miesięcy (-20%)' }.freeze

   TIME_OPTIONS_PAY = {
   '1month' => '1 miesiąc',
   '3months' => '3 miesiące',
   '6months' => '6 miesięcy',
   '12months' => '12 miesięcy' }.freeze
  


  private

   def not_referenced_by_any_business_cart_item
    unless business_cart_items.empty?
      errors.add(:base, 'Plan należy do czyjegoś koszyka')
      throw :abort
    end
   end
	
  
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController


  before_action :set_plan, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_manager!, except: [:index, :show]

  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.includes(:subscriptions).all.order("created_at asc")
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = current_manager.plans.build
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = current_manager.plans.build(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:brand, :model, :description, :condition, :finish, :title, :price, :image)
    end

end

app/helpers/plans_helper.rb
module PlansHelper

	def infinity
		content_tag(:i, 'all_inclusive', class: 'material-icons left infinity tooltipped', data: {position:"right", delay:"250", tooltip:"bez limitu" })
		
	end

	def select_all_time_options_plan
		arr ={}
		time_options = Plan::TIME_OPTIONS_ALL.map { |k,v| [v, k] }
		puts 
		#puts time_options
		time_options
	end

	def select_pay_time_options_plan
		puts 'pay_only time_options'
		time_options = Plan::TIME_OPTIONS_PAY.map { |k,v| k[v] }
		#puts time_options #['test'].remove

		time_options

	end


	def translate_time_sub_for_human
		time_options = Plan::TIME_OPTIONS_ALL.map { |k,v| [v, k] }
		puts time_options
		time_options
	end

	
	def price
		
	end

	def in_businees_cart?(plan)
		array = current_business_cart.business_cart_items.pluck(:plan_id)
		array.include?(plan)
	end

	def test_plan?
		current_business_cart.business_cart_items.test.first
	end

	def have_test_period?
		array = current_business_cart.business_cart_items.pluck(:period)
		array.include?('test')
	end
	

end
 

app/views/plans/_plan.html.erb
        <div id="plan_<%=plan.id%>" class="column white- col s12 m3 l3 hoverable- row left-align <%= plan.id == 3 ? 'z-depth-4 bestseller-frame' : '' %> ">

          
          <div class=" white-text center-align">
            
            <div class="col s12 plan_name blue darken-<%=plan.id%>">
              <%= plan.name %>
                
            </div>
            <%= plan.id == 3 ? '<div class="bestseller">Najczęściej wybierany </div>'.html_safe : '<div class="bestseller" style="visibility:hidden;"> &nbsp;</div>'.html_safe %>
          </div>
          <div class="row white blue-text  text-darken-<%=plan.id%>">
            <div class="col s12">
              <span style="font-size: 30px;"><%= plan.price.to_i %> zł / 
                <span style="font-size:16px;">miesiąc</span><br>
              </span>
            </div>
          </div>
          <div class="row white">
            <div class="col s12">
              <span class="blue-text text-darken-<%=plan.id%> number"><%= plan.sms_limit %></span>
               smsów</div>
             </div>
          <div class="row white">
            <div class="col s12">
              <span class="blue-text text-darken-<%=plan.id%> number"><%= plan.email_limit %></span>
               emaili</div>
             </div>
          <div class="row white">
            <div class="col s12">
              <span><%= infinity %> rezerwacji</span>
            </div>
          </div>
          <div class="row white">
            <div class="col s12">
              <span><%= infinity %> pracowników</span>
            </div>
          </div>
          <div class="row white">
            <div class="col s12">
              <span><%= infinity %> usług</span>
            </div>
          </div>
          
          <%= form_with url: business_cart_items_path, method: :post  do |f| %>

          <div class="row white no-divider no-padding">
            <div class="input-field col s12">

            <% unless current_business_cart.test_period_in_business_cart? %>
                <% f.select :period, options_for_select(
              select_all_time_options_plan) %>
              <%= f.collection_select(:subscription_id, plan.subscriptions, :id, :calculate_time_to_human) %>
            <% else %>
                  <%= f.select :period, options_for_select(
              select_pay_time_options_plan) %>
calculate_time_to_human
            <% end %> 
             <%= f.label 'Okres abonamentowy', for: 'period' %>
             
              <%= f.hidden_field :plan_id, value: plan.id %>
              <% f.number_field :quantity, value: 1, class: "number-tag", min: 1 %>
            </div>
          </div>

          <div class="row white center-align no-divider no-padding-top">
            <div class="center-align">
            <% unless in_businees_cart?(plan.id) %>
              <%= f.button nil, class: "btn-large waves-effect waves-light orange- accent-3- add_to_cart-  ", onclick:"M.toast({html: 'Dodano do koszyka'})" do %>
               <i class="material-icons left white-text cart_icon">local_grocery_store</i>Do&nbsp;koszyka 
              <% end %>
            <% else %>
              <%= f.button nil, class: "btn-large disabled  " do %>
               <i class="material-icons left cart_icon">local_grocery_store</i>W&nbsp;koszyku 
              <% end %>
            <% end %>
            </div>
          </div>
            <% end %>


        </div>

app/views/plans/index.html.erb
<% content_for :menu do %> <%= render 'layouts/business_navbar'%> <% end %>
<% 'SEO FRIENDLY' %>
<div class="jumbo center-align">
  <h1>Cennik</h1>
  <h2>Wybierz pakiet dla Twojego biznesu i zyskuj nowych klientów!</h2>
</div>
<div class="">
  <div class="container white-">
    <div  class=" row pricing-table ">
      <div id="plans_area">
        <%= render @plans %>
        </div>
    </div>
  </div>
</div>
<div class="background"></div>

<h2>Hello</h2>


             <div class="container">
  <div class="row">
    
  </div>     
</div>
      


<div class="primary white-text" ><br>Primary&nbsp;</div>
<div class="secondary white-text" ><br>Secondary&nbsp;</div>
<div class="dark white-text" ><br>Dark&nbsp;</div>
<div class="light black-text" ><br>Light&nbsp;</div>