config/routes.rb
Rails.application.routes.draw do
  
  scope(path_names: { new: 'aplikuj' }) do
    resources :ngos,  path: 'ambasador' , only: [:index, :new, :create] do
      get 'dziekujemy', on: :collection
      get 'scrapper_city', on: :collection
      get 'raport', on: :collection
    end
  end

  get 'welcome/index'


  root to: 'welcome#index'

  #get 'seo/show'
  #get 'business_carts/index'
  #resources :cities, path: '', only: :show
  #resources :categories, path: '', only: :show
  #resources :companies, path: '', only: :show

  #devise_for :managers
  devise_for :managers, path: 'secure',  controllers: { 
  	registrations: 'managers/registrations',
  	sessions: 'managers/sessions' },
  	path_names: { sign_in: 'login',
  	sign_out: 'logout',
  	password: 'secret',
  	confirmation: 'verification',
  	unlock: 'unblock',
  	registration: 'register',
  	sign_up: 'manager' }
  	
    get 'koszyk', to: 'carts#show', as: :cart
    get 'podsumowanie', to: 'carts#resume', as: :cart_resume
    get 'platnosc', to: 'carts#payment', as: :cart_payment
    get 'potwierdzenie', to: 'carts#confirm', as: :cart_confirm
    get 'panel', to: 'carts#panel', as: :panel
    
    resources :carts, path: 'koszyk' do
      
      member do
        get 'cart'
        
      end
      collection do
        patch 'set_kind'

      end
    end

    resources :orders, path: 'zamowienia'
  
    resources :services do
      resources :cart_items, shallow: true do
      member do
          get 'configured'
        end
      end
    end
  #get 'rejestracja-firmy', to: 'company#'
  #resources :cart_bussinesses

  get 'welcome/index'
  

  scope '/biznes' do
    get 'cennik', to: 'plans#index' 
    #get 'cart', to: 'business_carts#cart', as: 'business_cart'
    resources :business_carts, path: 'koszyk' do
      collection do
        get 'cart'
      end
    end
    resources :business_cart_items
  end

  get '/:id', to: 'seo#show', as: 'seo_link'

  root 'plans#index'
  
  #scope '/biznes' do
  #  get 'cart', to: 'business_carts#index', as: 'business_cart'
  #  resources :business_cart_items, only: [:create, :update, :destroy]
  #end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_admin_panel.html.erb
<nav style="position:fixed; z-index:999; margin-bottom:64px;">
    <div class="nav-wrapper">
      <ul class="left hide-on-med-and-down">
        <li><a href="sass.html"><i class="material-icons green-text text-ligten-3">lock</i></a></li>
        
      </ul>
      <a href="#!" class="brand-logo"><i class="material-icons">cloud</i>Logo</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="sass.html"><i class="material-icons">search</i></a></li>
        <li><a href="badges.html"><i class="material-icons">view_module</i></a></li>
        <li><a href="collapsible.html"><i class="material-icons">refresh</i></a></li>
        <li> <a href="collapsible.html" class="btn-floating waves-effect waves-light grey center-align" style="font-size: 1.4em;">AZ</a></li>
      </ul>
    </div>
  </nav>
      <!-- Navbar goes here -->

    <!-- Page Layout here -->
    <div class="row"  >

      <div class="col s3 l2 blue-grey darken-4" style="padding:0px !important; position: fixed; margin-top:64px;">
        
        
        <nav class="z-depth-0">
          <div class="nav-wrapper" style=" width:100% !important; ">
            
            <ul class="row" style="display:block; width:100%; margin: 0 !important;">
              <li class="col s12 blue-grey" style="padding:0px !important"><span><a href="/admin/pages"><i class="material-icons left" >content_copy</i><i class="material-icons right  blue-grey-text" style="position:relative; left:45px; font-size:50px;">play_arrow</i>Strony</a><div ></div></span></li>
              <li class="col s12" style="padding:0px !important"><a href="badges.html"><i class="material-icons left" style="padding:0px !important">collections</i>Media</a></li>
              <li class="col s12" style="padding:0px !important"><a href="badges.html"><i class="material-icons left" style="padding:0px !important">subscriptions</i>Slidery</a></li>
               <li><div class="divider white-text white"></div></li>

              <li class="col s12" style="padding:0px !important"><a href="badges.html"><i class="material-icons left" style="padding:0px !important">vertical_align_top</i>Nagłówki</a></li>
              
              <li class="col s12" style="padding:0px !important"><a href="badges.html"><i class="material-icons left" style="padding:0px !important">menu</i>Menu</a></li>
               <li class="col s12" style="padding:0px !important"><a href="badges.html"><i class="material-icons left" style="padding:0px !important">vertical_align_bottom</i>Stopka</a></li>
               <li class="col s12" style="padding:0px !important"><a href="badges.html"><i class="material-icons left" style="padding:0px !important">chat_bubble_outline</i>Formularze</a></li>
               
                <li class="col s12" style="padding:0px !important"><a href="badges.html"><i class="material-icons left" style="padding:0px !important">account_circle</i>Moje konto</a></li>
            </ul>
          </div>
        </nav>
            

        <!-- Grey navigation panel -->
        
      </div>

      <div class="col s9 l10 offset-s3 offset-l2 ">
        <nav class=" white blue-grey-text text-darken-3 z-depth-0">
        

          
      </nav>
        <%= yield %>
      </div>

    </div>

app/views/layouts/_ambassador_navbar.html.erb
<nav class="navbar-fixed white hide-" style="position:fixed; margin-bottom:60px; padding:1rem-; width:100% !important;  ">
    <div class="nav-wrapper row-100 white" style="z-index:99999; max-width:1201px;">
      <a href="#" class="brand-logo left- hide-"><div class="valign-wrapper">
          <svg id="logo" width="50" height="55" style="background-color:red-;">

   
   <circle id="circle" cx="25" cy="30" r="0" stroke="gray" stroke-width="5" fill="transparent"  />
   <line id="line-white" x1="25" y1="30" x2="25" y2="30" style="stroke:white;stroke-width:7.5" transform="rotate(0  25 25)" transform="origin(25 30)" />
   
   <line id="line-big" x1="25" y1="30" x2="25" y2="30" style="stroke:#00acc1 ;stroke-width:2.5" />
   
    <line id="line-big-accent" x1="25" y1="30" x2="25" y2="30" style="stroke:gold; stroke-width:2.5" />
 
 
  
    <line id="line-small" x1="15" y1="30" x2="15" y2="30" style="stroke:#00acc1 ;stroke-width:2.5 " />
   
   <line id="line-small-accent" x1="15" y1="30" x2="15" y2="30" style="stroke:gold;stroke-width:2.5 " />
   
   
        <animate 
           xlink:href="#circle"
           attributeName="r"
           from="2"
           to="20" 
           dur="100ms"
           begin="300ms"
           fill="freeze" />
  
        <animate 
           xlink:href="#circle"
           attributeName="stroke-width"
           from="2"
           to="5" 
           dur="100ms"
           begin="400ms"
           fill="freeze" />
        
           
           <animateTransform 
                xlink:href="#line-white"
                attributeType="xml"
                    attributeName="transform"
                    type="rotate"
                    from="0 25 30"
                    to="45 25 30"
                    dur="200ms"
                begin="500ms"
                    fill="freeze"/>
           
           <animateTransform 
                xlink:href="#line-big"
                attributeType="xml"
                    attributeName="transform"
                    type="rotate"
                    from="0 25 30"
                    to="45 25 30"
                    dur="200ms"
                begin="700ms"
                    fill="freeze"/>
                    
                     <animateTransform 
                xlink:href="#line-big-accent"
                attributeType="xml"
                    attributeName="transform"
                    type="rotate"
                    from="0 25 30"
                    to="45 25 30"
                    dur="200ms"
                begin="700ms"
                    fill="freeze"/>
                    
           <animateTransform 
                xlink:href="#line-small"
                attributeType="xml"
                    attributeName="transform"
                    type="rotate"
                    from="0 25 30"
                    to="45 25 30"
                    dur="200ms"
                begin="700ms"
                    fill="freeze"/>
                    
                     <animateTransform 
                xlink:href="#line-small-accent"
                attributeType="xml"
                    attributeName="transform"
                    type="rotate"
                    from="0 25 30"
                    to="45 25 30"
                    dur="200ms"
                begin="700ms"
                    fill="freeze"/>
                    
           <animate 
           xlink:href="#line-small"
           attributeName="x2"
           from="15"
           to="26" 
           dur="150ms"
           begin="1100ms"
           fill="freeze" />
           
            <animate 
           xlink:href="#line-small-accent"
           attributeName="x2"
           from="15"
           to="26" 
           dur="100ms"
           begin="1500ms"
            />
           
           <animate 
           xlink:href="#line-big"
           attributeName="y2"
           from="30"
           to="1" 
           dur="300ms"
           begin="1300ms"
           fill="freeze" />
           
            <animate 
           xlink:href="#line-big-accent"
           attributeName="y2"
           from="30"
           to="1" 
           dur="100ms"
           begin="1700ms"
            />
           
           <animate 
           xlink:href="#line-white"
           attributeName="y2"
           from="30"
           to="5" 
           dur="300ms"
           begin="1300ms"
           fill="freeze" />
           
           
           
           <animate 
           xlink:href="#circle"
           attributeName="stroke"
           from="blue"
           to="silver" 
           dur="300ms"
           begin="200ms"
           fill="freeze" />
           
            <animate 
           xlink:href="#circle"
           attributeName="stroke"
           from="silver"
           to="#ff7b25" 
           dur="300ms"
           begin="600ms"
           fill="freeze" />
   Sorry, your browser does not support inline SVG.
    </svg><span class="brand-text primary-text">rezervi<span class="trade">&trade;<span class="grey-text">&nbsp;&nbsp;Ambasador</span></span></span></div></a>

      
         
      <ul id="nav-mobile" class="right hide-on-med-and-down- hide ">

        

 
        <li><a href="#" class="btn-floating btn-flat secondary btn-large- waves-effect- waves-light- red-text-"><i class="material-icons red-text-">event</i></a></li>
        <li><a href="#" class="btn-floating btn-flat primary btn-large- waves-effect- waves-light- red-text-"><i class="material-icons red-text-">shopping_basket</i></a></li>
        <li><a href="#" class="btn-floating btn-flat default"><i class="material-icons">account_circle</i></a></li>
        <li><a href="#" class="sidenav-trigger btn-floating btn-flat default "><i class="material-icons dark-text- active-">menu</i></a></li>
        <li  class="hide">
          <a class="btn-floating btn-large white waves-effect waves-grey btn-flat "><svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" width="35px" height="56px"  version="1.1" style="shape-rendering:geometricPrecision; text-rendering:geometricPrecision; image-rendering:optimizeQuality; fill-rule:evenodd; clip-rule:evenodd"
        viewBox="0 0 2.05 1.74"
         xmlns:xlink="http://www.w3.org/1999/xlink">
         <defs>
          <style type="text/css">
           <![CDATA[
            .fil0 {fill:none}
            .fil1 {fill:#ff7b25 }
            .fil2 {fill:#00acc1}
           ]]>
          </style>
         </defs>
         <g id="Warstwa_x0020_1">
          <metadata id="CorelCorpID_0Corel-Layer"/>
          
          <path class="fil1" d="M1.52 0.64l-0.41 -0.6c-0.01,-0.03 -0.04,-0.04 -0.07,-0.04 -0.03,0 -0.06,0.01 -0.08,0.04l-0.4 0.6 -0.44 0c-0.05,0 -0.09,0.04 -0.09,0.09 0,0.01 0,0.02 0,0.03l0.24 0.85c0.02,0.07 0.09,0.13 0.17,0.13l1.19 0c0.09,0 0.16,-0.06 0.18,-0.13l0.23 -0.85 0.01 -0.03c0,-0.05 -0.04,-0.09 -0.09,-0.09l-0.44 0zm-0.76 0l0.28 -0.4 0.27 0.4 -0.55 0z"/>
          <circle class="fil2" cx="1.04" cy="1.2" r="0.54"/>
          <path class="fil1" d="M0.08 0.65c-0.03,0.01 -0.05,0.05 -0.05,0.08 0,0.01 0,0.02 0,0.03l0.24 0.85c0.02,0.07 0.09,0.13 0.17,0.13l1.19 0c0.09,0 0.16,-0.06 0.18,-0.13l0.23 -0.85 0.01 -0.03c0,-0.03 -0.02,-0.07 -0.05,-0.08l-1.92 0z"/>
         </g>
        </svg></a>
        </li>
      </ul>
    </div>
  </nav>

<% unless cookies[:cookie_info] %>
   <div id="cookie-info" class="row z-depth-1  white red-  vertial-align z-depth-1" style=" position:fixed; top:50; left:0; width:100%; margin:0;  padding: 15px; z-index:99; ">
    <div class="col s12">
Strona wykorzystuje pliki cookies w celu prawidłowego funkcjonowania serwisu. Możesz zmienić ustawienia swojej przeglądarki, jeśli nie chcesz zapisywać ich w swoim urządzeniu. <a><i id="cookie-close" class="material-icons right ">close</i> </a>
</div>
<% end %>
  </div>

  <script>
    $("#cookie-close").click(function() {
  $("#cookie-info").hide();
});
  </script>

app/views/layouts/_business_navbar.html.erb
 <nav class="navbar-fixed white">
    <div class="nav-wrapper" style="z-index:99999;  ">
      <a href="#" class="brand-logo left hide-"><div class="valign-wrapper">
          <%= render 'layouts/svgs/rezervi_logo' %><span class="primary-text">rezervi&trade;</span>
        </div>
        </a>

    
      
      <ul id="nav-mobile" class="right hide-on-med-and-down- left-align">

        

 

        
        <li  class="hide-">
          <%= link_to business_carts_path, class: "btn-floating btn-large white waves-effect waves-grey btn-flat indent" do  %>
           <div ><%= render '/layouts/svgs/cart' %></div>
           <% end %>
        </li>
        <li><a href="#"><i class="material-icons grey-text indent">business_center</i></a></li>
        <li><a href="#"><i class="material-icons grey-text active">menu</i></a></li>
      </ul>
    </div>
  </nav>



        

  

  <!-- Modal Structure -->
  <div id="modal1" class="modal bottom-sheet">
    <div class="modal-content">
      <h4>Twój koszyk</h4>
      <p>A bunch of text</p>
    </div>
    <div class="modal-footer">
      <a href="#!" data-turbolinks="false" class="modal-close waves-effect waves-green btn-flat">Zamknij</a>
    </div>
  </div>

app/views/layouts/_business_navbar_step_progress.html.erb
 <nav class="navbar-fixed white">
    <div class="nav-wrapper" style="z-index:99999;  ">
      <a href="#" class="brand-logo left hide-"><div class="valign-wrapper">
          <%= render 'layouts/svgs/rezervi_logo' %><span class="primary-text">rezervi&trade;</span></div></a>

  <% if current_business_cart && current_business_cart.cart_size > 0 %>
    <div class="container-progress-step vertical-align-" style="z-index:999;" >
        <ul class="progress-step three-step">
            <li class="active1"> <i class="material-icons icon small" style="">shopping_basket</i>Twój Koszyk</li>

            <li class="active1"><i class="material-icons icon" style="">account_circle</i>Twoje Konto</li>
            <li ><i class="material-icons icon" style="">monetization_on</i> Potwierdzenie</li>
        </ul>
    </div>
  <% end %>    
      <ul id="nav-mobile" class="right hide-on-med-and-down- left-align">

        

 

        
        <li  class="hide-">
          <%= link_to business_carts_path, class: "btn-floating btn-large white waves-effect waves-grey btn-flat indent" do  %>
           <div ><%= render '/layouts/svgs/cart' %></div>
           <% end %>
        </li>
        <li><a href="#"><i class="material-icons grey-text indent">business_center</i></a></li>
        <li><a href="#"><i class="material-icons grey-text active">menu</i></a></li>
      </ul>
    </div>
  </nav>



        

  

  <!-- Modal Structure -->
  <div id="modal1" class="modal bottom-sheet">
    <div class="modal-content">
      <h4>Twój koszyk</h4>
      <p>A bunch of text</p>
    </div>
    <div class="modal-footer">
      <a href="#!" data-turbolinks="false" class="modal-close waves-effect waves-green btn-flat">Zamknij</a>
    </div>
  </div>

app/views/layouts/_navbar.html.erb
<nav class="navbar-fixed white hide-" style="position:fixed; margin-bottom:60px; padding:1rem-; width:100% !important;  ">
    <div class="nav-wrapper row-100 white" style="z-index:99999; max-width:1201px;">
      <a href="#" class="brand-logo left hide-"><div class="valign-wrapper">
          <svg id="logo" width="50" height="55" style="background-color:red-;">

   
   <circle id="circle" cx="25" cy="30" r="0" stroke="gray" stroke-width="5" fill="transparent"  />
   <line id="line-white" x1="25" y1="30" x2="25" y2="30" style="stroke:white;stroke-width:7.5" transform="rotate(0  25 25)" transform="origin(25 30)" />
   
   <line id="line-big" x1="25" y1="30" x2="25" y2="30" style="stroke:#00acc1 ;stroke-width:2.5" />
   
    <line id="line-big-accent" x1="25" y1="30" x2="25" y2="30" style="stroke:gold; stroke-width:2.5" />
 
 
  
    <line id="line-small" x1="15" y1="30" x2="15" y2="30" style="stroke:#00acc1 ;stroke-width:2.5 " />
   
   <line id="line-small-accent" x1="15" y1="30" x2="15" y2="30" style="stroke:gold;stroke-width:2.5 " />
   
   
        <animate 
           xlink:href="#circle"
           attributeName="r"
           from="2"
           to="20" 
           dur="100ms"
           begin="300ms"
           fill="freeze" />
  
        <animate 
           xlink:href="#circle"
           attributeName="stroke-width"
           from="2"
           to="5" 
           dur="100ms"
           begin="400ms"
           fill="freeze" />
        
           
           <animateTransform 
                xlink:href="#line-white"
                attributeType="xml"
                    attributeName="transform"
                    type="rotate"
                    from="0 25 30"
                    to="45 25 30"
                    dur="200ms"
                begin="500ms"
                    fill="freeze"/>
           
           <animateTransform 
                xlink:href="#line-big"
                attributeType="xml"
                    attributeName="transform"
                    type="rotate"
                    from="0 25 30"
                    to="45 25 30"
                    dur="200ms"
                begin="700ms"
                    fill="freeze"/>
                    
                     <animateTransform 
                xlink:href="#line-big-accent"
                attributeType="xml"
                    attributeName="transform"
                    type="rotate"
                    from="0 25 30"
                    to="45 25 30"
                    dur="200ms"
                begin="700ms"
                    fill="freeze"/>
                    
           <animateTransform 
                xlink:href="#line-small"
                attributeType="xml"
                    attributeName="transform"
                    type="rotate"
                    from="0 25 30"
                    to="45 25 30"
                    dur="200ms"
                begin="700ms"
                    fill="freeze"/>
                    
                     <animateTransform 
                xlink:href="#line-small-accent"
                attributeType="xml"
                    attributeName="transform"
                    type="rotate"
                    from="0 25 30"
                    to="45 25 30"
                    dur="200ms"
                begin="700ms"
                    fill="freeze"/>
                    
           <animate 
           xlink:href="#line-small"
           attributeName="x2"
           from="15"
           to="26" 
           dur="150ms"
           begin="1100ms"
           fill="freeze" />
           
            <animate 
           xlink:href="#line-small-accent"
           attributeName="x2"
           from="15"
           to="26" 
           dur="100ms"
           begin="1500ms"
            />
           
           <animate 
           xlink:href="#line-big"
           attributeName="y2"
           from="30"
           to="1" 
           dur="300ms"
           begin="1300ms"
           fill="freeze" />
           
            <animate 
           xlink:href="#line-big-accent"
           attributeName="y2"
           from="30"
           to="1" 
           dur="100ms"
           begin="1700ms"
            />
           
           <animate 
           xlink:href="#line-white"
           attributeName="y2"
           from="30"
           to="5" 
           dur="300ms"
           begin="1300ms"
           fill="freeze" />
           
           
           
           <animate 
           xlink:href="#circle"
           attributeName="stroke"
           from="blue"
           to="silver" 
           dur="300ms"
           begin="200ms"
           fill="freeze" />
           
            <animate 
           xlink:href="#circle"
           attributeName="stroke"
           from="silver"
           to="#ff7b25" 
           dur="300ms"
           begin="600ms"
           fill="freeze" />
   Sorry, your browser does not support inline SVG.
    </svg><span class="brand-text primary-text">rezervi<span class="trade">&trade;</span></span></div></a>

      
         
      <ul id="nav-mobile" class="right hide-on-med-and-down- ">

        

 
        
        <li>
        <span id="cart"><%= render 'carts/cart' rescue ' ' %></span>
        </li>
        <li>
          <%= link_to orders_path, class: 'btn-floating btn-flat secondary' do %>
            <i class="material-icons ">event</i>
          <% end %>
        </li>
        <li><a href="#" class="btn-floating btn-flat default"><i class="material-icons">account_circle</i></a></li>
        <li><a href="#" class="sidenav-trigger btn-floating btn-flat default "><i class="material-icons dark-text- active-">menu</i></a></li>
        <li  class="hide">
          <a class="btn-floating btn-large white waves-effect waves-grey btn-flat "><svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" width="35px" height="56px"  version="1.1" style="shape-rendering:geometricPrecision; text-rendering:geometricPrecision; image-rendering:optimizeQuality; fill-rule:evenodd; clip-rule:evenodd"
        viewBox="0 0 2.05 1.74"
         xmlns:xlink="http://www.w3.org/1999/xlink">
         <defs>
          <style type="text/css">
           <![CDATA[
            .fil0 {fill:none}
            .fil1 {fill:#ff7b25 }
            .fil2 {fill:#00acc1}
           ]]>
          </style>
         </defs>
         <g id="Warstwa_x0020_1">
          <metadata id="CorelCorpID_0Corel-Layer"/>
          
          <path class="fil1" d="M1.52 0.64l-0.41 -0.6c-0.01,-0.03 -0.04,-0.04 -0.07,-0.04 -0.03,0 -0.06,0.01 -0.08,0.04l-0.4 0.6 -0.44 0c-0.05,0 -0.09,0.04 -0.09,0.09 0,0.01 0,0.02 0,0.03l0.24 0.85c0.02,0.07 0.09,0.13 0.17,0.13l1.19 0c0.09,0 0.16,-0.06 0.18,-0.13l0.23 -0.85 0.01 -0.03c0,-0.05 -0.04,-0.09 -0.09,-0.09l-0.44 0zm-0.76 0l0.28 -0.4 0.27 0.4 -0.55 0z"/>
          <circle class="fil2" cx="1.04" cy="1.2" r="0.54"/>
          <path class="fil1" d="M0.08 0.65c-0.03,0.01 -0.05,0.05 -0.05,0.08 0,0.01 0,0.02 0,0.03l0.24 0.85c0.02,0.07 0.09,0.13 0.17,0.13l1.19 0c0.09,0 0.16,-0.06 0.18,-0.13l0.23 -0.85 0.01 -0.03c0,-0.03 -0.02,-0.07 -0.05,-0.08l-1.92 0z"/>
         </g>
        </svg></a>
        </li>
      </ul>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  	  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
      <meta name="robots" content="noindex, nofollow">
      <link href="https://fonts.googleapis.com/css?family=Roboto:100,400" rel="stylesheet"> 
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Rezervi&trade;</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="overlay">
    <div id="modal"></div>
  </div>
  <!--  Breadcrumbs start-->
 
  <!--  Breadcrumbs end-->
  <%= yield :menu  %>
    <div style="margin-top:64px;"></div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>